version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    target-branch: main
    open-pull-requests-limit: 3
    schedule:
      interval: weekly
    labels:
      - maintenance
    commit-message:
      prefix: "[DEPENDABOT]"

  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "main"
    open-pull-requests-limit: 50
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: org.springframework.cloud:spring-cloud-dependencies
        versions:
          - ">= 2022"
      - dependency-name: com.alibaba.cloud:spring-cloud-alibaba-dependencies
        versions:
          - ">= 2021.1"
      - dependency-name: org.springframework.security:spring-security-oauth2-authorization-server
        versions:
          - ">= 1"
      - dependency-name: org.springframework.boot:spring-boot-dependencies
        versions:
          - ">= 3"
      - dependency-name: de.codecentric:spring-boot-admin-dependencies
        versions:
          - ">= 3"
      - dependency-name: com.xuxueli:xxl-job-core
        versions:
          - ">= 3"
      - dependency-name: org.mybatis.spring.boot:mybatis-spring-boot-starter
        versions:
          - ">= 3"
      - dependency-name: net.logstash.logback:logstash-logback-encoder
        versions:
          - ">= 8"
      - dependency-name: io.sundr:sundr-maven-plugin
        versions:
          - ">= 0.2"
      - dependency-name: com.mycila:license-maven-plugin
        versions:
          - ">= 5"
      - dependency-name: com.github.ekryd.sortpom:sortpom-maven-plugin
        versions:
          - ">= 3"
