# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all handler options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# 文件的配置选项：https://docs.github.com/zh/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# 自定义依赖项更新：https://docs.github.com/zh/code-security/dependabot/dependabot-version-updates/customizing-dependency-updates
# 管理依赖项更新的所有拉取请求：https://docs.github.com/zh/code-security/dependabot/working-with-dependabot/managing-pull-requests-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    target-branch: main
    open-pull-requests-limit: 3
    schedule:
      interval: weekly
    labels:
      - DEPENDABOT
    commit-message:
      prefix: "[DEPENDABOT]"

  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "main"
    open-pull-requests-limit: 50
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Shanghai"
      ignore:
        - dependency-name: org.springframework.cloud:spring-cloud-dependencies
          versions:
            - ">= 2022"
        - dependency-name: com.alibaba.cloud:spring-cloud-alibaba-dependencies
          versions:
            - "= 2021.1"
            - ">= 2022"
        - dependency-name: org.springframework.security:spring-security-oauth2-authorization-server
          versions:
            - ">= 1"
            - ">= 1.1"
        - dependency-name: org.springframework.boot:spring-boot-dependencies
          versions:
            - ">= 3"
        - dependency-name: org.springframework.boot:spring-boot-starter-security
          versions:
            - ">= 3"
        - dependency-name: org.springframework.boot:spring-boot-maven-support
          versions:
            - ">= 3"
        - dependency-name: de.codecentric:spring-boot-admin-dependencies
          versions:
            - ">= 3"
