_extends: .github
name-template: '$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: 🚀 New features
    labels:
      - enhancement
      - feature
  - title: 🐛 Bug fixes
    labels:
      - bug
      - fix
      - hotfix
      - bugfix
  - title: 📝 Documentation updates
    labels:
      - documentation
      - localization
  - title: 🚦Tests
    labels:
      - test
      - tests
  - title: 🧰 Dependency updates
    labels:
      - dependencies
      - dependabot
      - DEPENDABOT
    collapse-after: 15

exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog
  - invalid

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/bugfix\/.+/'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'

version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
      - enhancement
  patch:
    labels:
      - patch
  default: patch
  
template: |
  ## What’s Changed

  $CHANGES

  All contributors: $CONTRIBUTORS
