_extends: .github
name-template: '$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
      - enhancement
  patch:
    labels:
      - patch
  default: patch

template: |
  ## What’s Changed

  $CHANGES

  All contributors: $CONTRIBUTORS
