name: Release to Maven Central

on:
  workflow_dispatch:

env:
  MAVEN_ARGS: -B -e -ntp

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Build and Test
        run: mvn clean verify

      - name: Release to Maven Central
        run: |
          mvn -Pjavadoc -Prelease deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.SIGNING_PASSPHRASE }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Publish Docker Image
        run: |
          mvn -pl rose-microservice/rose-upms/rose-upms-service spring-boot:build-image -DskipTests
          docker push ${{ secrets.DOCKER_USERNAME }}/rose-upms-service
