name: PR Automation
on:
  pull_request_target:
    types:
      - closed


jobs:
  pr-automation:
    name: PR Automation
    uses: apache/maven-gh-actions-shared/.github/workflows/pr-automation.yml@v4
