name: Release Drafter
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_release_draft:
    uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5  # v6
